stage1:
  base_lr: 0.00005 # 0.00005 original
  disc_lr: 0.0001 # 0.0001 original
  perceptual_weight: 0.002
  adv_weight: 0.005 #0.005 original
  kl_weight: 0.000001 # 000001 original
  params:
    spatial_dims: 2
    in_channels: 1
    out_channels: 1
    num_channels: [128, 128] # [128, 128] Original
    latent_channels: 15 # 15
    num_res_blocks: 2
    attention_levels: [False, False]
    #with_encoder_nonlocal_attn: False # sem
    #with_decoder_nonlocal_attn: False # sem

discriminator:
  params:
    spatial_dims: 2
    num_channels: 64
    num_layers_d: 3
    in_channels: 1

perceptual_network:
  params:
    spatial_dims: 2
    network_type: "alex" #alex